name: "Close stale issues"

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  # This allows you to run the workflow manually from the GitHub Actions tab

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue has been automatically closed because it has not had any recent activity."
          days-before-stale: 30
          days-before-close: 0
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-pr-message: "This pull request has been automatically closed because it has not had any recent activity."
          days-before-stale-pr: 30
          days-before-close-pr: 0
